#ifndef FUNNYOS_BOOTLOADER_BOOTLOADER32_SRC_INTERRUPTS_HPP
#define FUNNYOS_BOOTLOADER_BOOTLOADER32_SRC_INTERRUPTS_HPP

namespace FunnyOS::Bootloader32 {

    void SetupInterrupts();

}

#endif  // FUNNYOS_BOOTLOADER_BOOTLOADER32_SRC_INTERRUPTS_HPP
