#ifndef FUNNYOS_KERNEL_BASE_HEADERS_FUNNYOS_KERNEL_VMM_VIRTUALMEMORYMANAGER_HPP
#define FUNNYOS_KERNEL_BASE_HEADERS_FUNNYOS_KERNEL_VMM_VIRTUALMEMORYMANAGER_HPP

namespace FunnyOS::Kernel::VMM {

    class VirtualMemoryManager {

    };

}

#endif  // FUNNYOS_KERNEL_BASE_HEADERS_FUNNYOS_KERNEL_VMM_VIRTUALMEMORYMANAGER_HPP
